name: Build source
on:
  push:
    branches: [ main ]
jobs:
  build-qooxdoo:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository 1
      uses: actions/checkout@v3
    - name: repository 2
      uses: actions/checkout@v3
      with:
        repository: MinhLam6969/test-repo1
    - name: Show working directory
      run: ls
